# Same as the previous query but now with the number of the LIMIT clause decreased to 500k.

SELECT ?var1 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .
 OPTIONAL {
  ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var2 .
 FILTER (  ( (  LANG (  ?var2  )  =  "en" ) ) 
) .
 }
}
LIMIT 500000
