SELECT ?var1 
WHERE {
  ?var1  <http://www.wikidata.org/entity/P31>  <http://www.wikidata.org/entity/Q5> .
 OPTIONAL {
  ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var2 .
 FILTER (  ( (  LANG (  ?var2  )  =  "en" ) ) 
) .
 }
}
